# Generated by Django 2.1.5 on 2019-01-23 11:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameEng', models.CharField(max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.PositiveSmallIntegerField()),
                ('Points', models.PositiveIntegerField()),
                ('WordsLearnt', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('Exelearnt', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('FunFacts', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('LangId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Language')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoginName', models.CharField(max_length=20, unique=True)),
                ('Password', models.CharField(max_length=20, unique=True)),
                ('Email', models.CharField(max_length=20)),
                ('LangDisplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameEng', models.CharField(max_length=20, unique=True)),
                ('Phonetics', models.CharField(max_length=20)),
                ('IsEnabled', models.BooleanField(default=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wordjp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameHira', models.CharField(max_length=20)),
                ('NameKata', models.CharField(max_length=20)),
                ('NameKanji', models.CharField(max_length=20)),
                ('NameRoma', models.CharField(max_length=20)),
                ('NameEng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Word')),
            ],
        ),
        migrations.AddField(
            model_name='progression',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.User'),
        ),
    ]
