# Generated by Django 2.1.5 on 2019-01-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='Code',
            field=models.CharField(default=None, max_length=7, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='NameEng',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
