# Generated by Django 2.1.5 on 2019-01-28 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20190123_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameEng', models.CharField(max_length=20)),
                ('NameFr', models.CharField(max_length=20)),
                ('Word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Word')),
            ],
        ),
    ]
