# Generated by Django 2.1.5 on 2019-01-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='Word',
        ),
        migrations.AddField(
            model_name='theme',
            name='words',
            field=models.ManyToManyField(blank=True, related_name='themes', to='learn.Word'),
        ),
    ]
