# Generated by Django 2.1.5 on 2019-03-11 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0005_auto_20190128_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usercustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoginName', models.CharField(max_length=20, unique=True)),
                ('Password', models.CharField(max_length=20, unique=True)),
                ('Email', models.CharField(max_length=20)),
                ('LangDisplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Language')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='LangDisplay',
        ),
        migrations.AlterField(
            model_name='progression',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Usercustom'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='usercustom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
