# Generated by Django 2.1.5 on 2019-03-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_auto_20190311_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='LoginName',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='Password',
        ),
    ]
