# Generated by Django 2.1.5 on 2019-03-11 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_auto_20190311_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
