# Generated by Django 2.1.5 on 2019-03-11 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_auto_20190311_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='Email',
        ),
    ]
