# Generated by Django 2.1.5 on 2019-03-21 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_progression_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordfr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phonetics', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=30)),
                ('NameEng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Wordru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phonetics', models.CharField(max_length=20)),
                ('NameRu', models.CharField(max_length=20)),
                ('NameRoma', models.CharField(max_length=20)),
                ('NameEng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Word')),
            ],
        ),
    ]
