# Generated by Django 2.1.5 on 2019-04-02 18:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0011_wordfr_wordru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.PositiveIntegerField()),
                ('WordList', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
                ('Total', models.PositiveIntegerField()),
                ('Difficulty', models.PositiveIntegerField()),
                ('Mode', models.CharField(max_length=20)),
                ('State', models.PositiveIntegerField()),
                ('Progression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Progression')),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='NameEng',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
