# Generated by Django 2.1.5 on 2019-04-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0012_auto_20190402_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='IsEnabled',
            field=models.BooleanField(default=True, max_length=20),
        ),
    ]
