# Generated by Django 2.1.5 on 2019-05-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0013_theme_isenabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordfr',
            name='Name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='wordfr',
            name='Phonetics',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='wordjp',
            name='NameHira',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='wordjp',
            name='NameKanji',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='wordjp',
            name='NameKata',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='wordjp',
            name='NameRoma',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='wordjp',
            name='Phonetics',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='wordru',
            name='NameRoma',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='wordru',
            name='NameRu',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='wordru',
            name='Phonetics',
            field=models.CharField(max_length=40),
        ),
    ]
